namespace Clatter.Unity
{
    /// <summary>
    /// A sound generated by an impact event and `ClatterManager`. An ImpactSound self-destructs when the audio is done playing.
    /// </summary>
    public class ImpactSound : Sound
    {
        /// <summary>
        /// Invoked whenever an audio clip ends.
        /// </summary>
        protected override void OnAudioClipEnd()
        {
            End();
        }
    }
}