namespace Clatter.Unity
{
    /// <summary>
    /// A sound generated by an impact event.
    /// </summary>
    public class ImpactSound : Sound
    {
        protected override void OnAudioClipEnd()
        {
            End();
        }
    }
}